// <auto-generated />
using System;
using DVLD.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DVLD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ApplicationTypeId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PaidFees")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationTypeId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("Applications", t =>
                        {
                            t.HasCheckConstraint("CK_Application_PaidFees_Positive", "[PaidFees] > 0");
                        });
                });

            modelBuilder.Entity("ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "019f016b-5d2c-7838-8817-b9bda94e8ded",
                            ConcurrencyStamp = "019f01db-ea48-73e7-8e51-4738f9a74412",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "019f016b-5d2c-7838-8817-b9bf6308b890",
                            ConcurrencyStamp = "019f01db-ea48-73e7-8e51-473dfbc6bcd6",
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Member"
                        });
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FourthName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThirdName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "019f016b-5d2c-7838-8817-b9b9f916ab20",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "019f016b-5d2c-7838-8817-b9bb05c255fd",
                            CountryId = 1,
                            Email = "admin@dvld.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            FourthName = "Admin",
                            IsDisabled = false,
                            LockoutEnabled = false,
                            NationalId = "12099328323432",
                            NormalizedEmail = "ADMIN@DVLD.COM",
                            NormalizedUserName = "ADMIN@DVLD.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEHzKyIJPL0TIfoWgyTljHrOrXksVLJsfc7WAvE8VgVuSK/rIQEDjOdG7+VbEZNtZg==",
                            PhoneNumberConfirmed = false,
                            SecondName = "Admin",
                            SecurityStamp = "019f016b-5d2c-7838-8817-b9ba67e52df0",
                            ThirdName = "Admin",
                            TwoFactorEnabled = false,
                            UserName = "admin@dvld.com"
                        });
                });

            modelBuilder.Entity("DVLD.Entities.ApplicationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ApplicationTypes", t =>
                        {
                            t.HasCheckConstraint("CK_Application_PaidFees_Positive", "[Fees] > 0")
                                .HasName("CK_Application_PaidFees_Positive1");
                        });
                });

            modelBuilder.Entity("DVLD.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cabo Verde"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 36,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 37,
                            Name = "China"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Congo (Republic of the)"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Cote d'Ivoire"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 53,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            Name = "India"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 122,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 123,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 127,
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 128,
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 147,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 149,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 161,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 162,
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 163,
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 170,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 181,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 182,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 183,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 184,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 185,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 186,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 193,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 194,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 195,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("DVLD.Entities.Driver", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("UpdatedById");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DVLD.Entities.DrivingLicenseApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LicenseTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId")
                        .IsUnique();

                    b.HasIndex("LicenseTypeId")
                        .IsUnique();

                    b.ToTable("DrivingLicenseApplications");
                });

            modelBuilder.Entity("DVLD.Entities.License", b =>
                {
                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicaitonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriverId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("IssueReason")
                        .HasColumnType("int");

                    b.Property<int>("LicenseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PaidFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("LicenseNumber");

                    b.HasIndex("ApplicaitonId")
                        .IsUnique();

                    b.HasIndex("CreatedById");

                    b.HasIndex("DriverId");

                    b.HasIndex("LicenseTypeId")
                        .IsUnique();

                    b.HasIndex("UpdatedById");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("DVLD.Entities.LicenseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DefaultValidityLength")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinimumAllowedAge")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LicenseType", null, t =>
                        {
                            t.HasCheckConstraint("CK_LicenseTypes_Fees", "[Fees] >= 0");

                            t.HasCheckConstraint("CK_LicenseTypes_MinimumAllowedAge", "[MinimumAllowedAge] >= 18");
                        });
                });

            modelBuilder.Entity("DVLD.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("DVLD.Entities.Test", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TestAppointmentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TestResult")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TestAppointmentId")
                        .IsUnique();

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("DVLD.Entities.TestAppointment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrivingLicenseApplicationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("PaidFees")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DrivingLicenseApplicationId");

                    b.HasIndex("TestTypeId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("UserId");

                    b.ToTable("TestAppointments");
                });

            modelBuilder.Entity("DVLD.Entities.TestType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Fees")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("TestTypes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "Permissions",
                            ClaimValue = "applications:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "Permissions",
                            ClaimValue = "applications:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "Permissions",
                            ClaimValue = "applications:update",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "Permissions",
                            ClaimValue = "application-types:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "Permissions",
                            ClaimValue = "application-types:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "Permissions",
                            ClaimValue = "application-types:update",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "Permissions",
                            ClaimValue = "application-types:delete",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "Permissions",
                            ClaimValue = "drivers:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 9,
                            ClaimType = "Permissions",
                            ClaimValue = "drivers:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "Permissions",
                            ClaimValue = "driving-license-applications:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "Permissions",
                            ClaimValue = "driving-license-applications:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "Permissions",
                            ClaimValue = "licenses:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "Permissions",
                            ClaimValue = "licenses:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "Permissions",
                            ClaimValue = "licenses:update",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "Permissions",
                            ClaimValue = "license-types:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "Permissions",
                            ClaimValue = "license-types:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "Permissions",
                            ClaimValue = "license-types:update",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "Permissions",
                            ClaimValue = "test-appointments:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 19,
                            ClaimType = "Permissions",
                            ClaimValue = "test-appointments:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 20,
                            ClaimType = "Permissions",
                            ClaimValue = "test-appointments:update",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "Permissions",
                            ClaimValue = "tests:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 22,
                            ClaimType = "Permissions",
                            ClaimValue = "roles:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 23,
                            ClaimType = "Permissions",
                            ClaimValue = "roles:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 24,
                            ClaimType = "Permissions",
                            ClaimValue = "roles:update",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "Permissions",
                            ClaimValue = "test-types:read",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 26,
                            ClaimType = "Permissions",
                            ClaimValue = "test-types:create",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 27,
                            ClaimType = "Permissions",
                            ClaimValue = "test-types:update",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        },
                        new
                        {
                            Id = 28,
                            ClaimType = "Permissions",
                            ClaimValue = "test-types:delete",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "019f016b-5d2c-7838-8817-b9b9f916ab20",
                            RoleId = "019f016b-5d2c-7838-8817-b9bda94e8ded"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Application", b =>
                {
                    b.HasOne("DVLD.Entities.ApplicationType", "ApplicationType")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApplicationUser", "User")
                        .WithMany("Applications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationType");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.HasOne("DVLD.Entities.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "UsreCreated")
                        .WithMany("Users")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");

                    b.Navigation("UsreCreated");
                });

            modelBuilder.Entity("DVLD.Entities.Driver", b =>
                {
                    b.HasOne("ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("DVLD.Entities.Driver", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApplicationUser");

                    b.Navigation("CreatedBy");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DVLD.Entities.DrivingLicenseApplication", b =>
                {
                    b.HasOne("Application", "Application")
                        .WithOne("DrivingLicenseApplication")
                        .HasForeignKey("DVLD.Entities.DrivingLicenseApplication", "ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Entities.LicenseType", "LicenseType")
                        .WithOne("DrivingLicenseApplication")
                        .HasForeignKey("DVLD.Entities.DrivingLicenseApplication", "LicenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("LicenseType");
                });

            modelBuilder.Entity("DVLD.Entities.License", b =>
                {
                    b.HasOne("Application", "Application")
                        .WithOne()
                        .HasForeignKey("DVLD.Entities.License", "ApplicaitonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Entities.Driver", "Driver")
                        .WithMany("Licenses")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Entities.LicenseType", "LicenseType")
                        .WithOne()
                        .HasForeignKey("DVLD.Entities.License", "LicenseTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Application");

                    b.Navigation("CreatedBy");

                    b.Navigation("Driver");

                    b.Navigation("LicenseType");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("DVLD.Entities.RefreshToken", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Entities.Test", b =>
                {
                    b.HasOne("ApplicationUser", "ApplicationUser")
                        .WithMany("Tests")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Entities.TestAppointment", "TestAppointment")
                        .WithOne("Test")
                        .HasForeignKey("DVLD.Entities.Test", "TestAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("TestAppointment");
                });

            modelBuilder.Entity("DVLD.Entities.TestAppointment", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany("TestAppointments")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Entities.DrivingLicenseApplication", "DrivingLicenseApplication")
                        .WithMany("TestAppointments")
                        .HasForeignKey("DrivingLicenseApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DVLD.Entities.TestType", "TestType")
                        .WithMany("TestAppointments")
                        .HasForeignKey("TestTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ApplicationUser", "AppointmentOwner")
                        .WithMany("OwnedAppointments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppointmentOwner");

                    b.Navigation("CreatedBy");

                    b.Navigation("DrivingLicenseApplication");

                    b.Navigation("TestType");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Application", b =>
                {
                    b.Navigation("DrivingLicenseApplication");
                });

            modelBuilder.Entity("ApplicationUser", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("OwnedAppointments");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TestAppointments");

                    b.Navigation("Tests");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("DVLD.Entities.ApplicationType", b =>
                {
                    b.Navigation("Applications");
                });

            modelBuilder.Entity("DVLD.Entities.Country", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DVLD.Entities.Driver", b =>
                {
                    b.Navigation("Licenses");
                });

            modelBuilder.Entity("DVLD.Entities.DrivingLicenseApplication", b =>
                {
                    b.Navigation("TestAppointments");
                });

            modelBuilder.Entity("DVLD.Entities.LicenseType", b =>
                {
                    b.Navigation("DrivingLicenseApplication")
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Entities.TestAppointment", b =>
                {
                    b.Navigation("Test")
                        .IsRequired();
                });

            modelBuilder.Entity("DVLD.Entities.TestType", b =>
                {
                    b.Navigation("TestAppointments");
                });
#pragma warning restore 612, 618
        }
    }
}
