using DVLD.Contracts.LicenseType;

namespace DVLD.Contracts.DrivingLicenseApplication;

public record DrivingLicenseApplicationResponse(ApplicationResponse ApplicationResponse, LicenseTypeResponse LicenseTypeResponse);
